<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<Version>1.0.0</Version>
		<Copyright>$([System.DateTime]::Now.Year) Noah Severyn</Copyright>

		<ApplicationIcon />

		<OutputType>Library</OutputType>
		<Nullable>enable</Nullable>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />

	<ItemGroup>
		<None Remove="Properties\new_properties.xml" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Properties\new_properties.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

</Project>
